services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Rome}
    volumes:
      - ${APPDATA_DIR:-/opt/iiot-irrigation-telecontrol/appdata}/beets/config:/config
      - ${MEDIA_DIR:-/opt/iiot-irrigation-telecontrol/media}/music:/music
      - ${MEDIA_DIR:-/opt/iiot-irrigation-telecontrol/media}/ingest:/downloads
    networks:
      - iiot_internal
    ports:
      - 8337:8337
    labels:
      - homepage.group=Multimedia
      - homepage.name=Beets
      - homepage.description=Music library manager
      - homepage.icon=beets
      - homepage.href=http://${SYS_IP}:8337
    restart: unless-stopped
networks:
  iiot_internal:
    external: true
