services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    labels:
      # - autoheal=true
      - homepage.group=Applications
      - homepage.name=Omni Tools
      - homepage.description=Pdf, img, txt and video utility
      - homepage.icon=omni-tools
      - homepage.href=http://${SYS_IP}:8090
    ports:
      - 8090:80
    restart: unless-stopped
    networks:
      - iiot_internal
networks:
  iiot_internal:
    external: true
