services:
  flame:
    container_name: flame
    ports:
      - 5005:5005
    volumes:
      - ${APPDATA_DIR:-/opt/appdata}/flame/data:/app/data
    environment:
      - PASSWORD=${FLAME_PASSWORD}
    image: pawelmalak/flame:latest
    networks:
      - iiot_internal
    restart: unless-stopped
    labels:
      - homepage.name=Flame
      - homepage.icon=flame
      - homepage.group=Monitors
      - homepage.description=Home page Statica
      - homepage.href=http://${SYS_IP}:5005

networks:
  iiot_internal:
    external: true
