---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Accesso Operativo:
    - Homepage:
        - icon: homepage.png
          abbr: HP
          href: http://{{HOMEPAGE_VAR_SYS_IP}}:3000
          description: Dashboard servizi locali
    - Dockge:
        - icon: dockge.png
          abbr: DG
          href: http://{{HOMEPAGE_VAR_SYS_IP}}:5001
          description: Gestione stack compose
    - Portainer:
        - icon: portainer.png
          abbr: PT
          href: https://{{HOMEPAGE_VAR_SYS_IP}}:9443
          description: Gestione container e volumi
    - WUD:
        - icon: wud.png
          abbr: WUD
          href: https://{{HOMEPAGE_VAR_SYS_IP}}:8000
          description: Gestione aggiornamenti 

- Infrastruttura:
    - Linux:
        - icon: linux
          abbr: LX
          href: https://www.debian.org
          description: Sistema Operativo
    - Proxmox:
        - icon: proxmox
          abbr: PM
          href: https://www.proxmox.com
          description: Virtualizzazione e containerizzazione [Hypervisor]
    - Docker:
        - icon: docker
          abbr: DK
          href: https://www.docker.com
          description: Virtualizzazione e containerizzazione [Container]

- C.B.U. Network:
    - Sito C.B.U.:
        - icon: homepage
          abbr: HP
          href: http://www.bonificaumbra.it
          description: Portale istituzionale

    - Facebook:
        - icon: facebook
          abbr: FB
          href: https://www.facebook.com/consorziobonificazione.umbra

    - Email:
        - icon: mail
          abbr: EM
          href: mailto:info@bonificaumbra.it
          description: invia email a @bonificaumbra

- Developer Network:
    - GitHub:
        - icon: github
          abbr: GH
          href: https://github.com/buoncri
          description: Repository e versionamento

    - LinkedIn:
        - icon: linkedin
          abbr: LI
          href: https://www.linkedin.com/in/buoncri
          description: Profilo professionale

    - Email:
        - icon: mail
          abbr: EM
          href: mailto:buoncri@libero.it
          description: invia email a @buoncri

- Finanziamenti FEASR:
    - Unione Europea:
        - icon: icons/ue.png
          abbr: UE
          href: https://european-union.europa.eu/
          description: Fondo Europeo Agricolo per lo Sviluppo Rurale
    - Masaf:
        - icon: icons/repubblica.png
          abbr: MASAF
          href: https://www.politicheagricole.it/
          description: Ministero dell'agricoltura, della sovranità alimentare e delle foreste
    - Regione Umbria:
        - icon: icons/regione_umbria.png
          abbr: RU
          href: https://www.regione.umbria.it/agricoltura
          description: Sviluppo Rurale
    - CSR Umbria:
        - icon: icons/csr.png
          abbr: CSR
          href: https://www.regione.umbria.it/csrumbria
          description: Complemento di Sviluppo Rurale per l'Umbria 2023-2027
