---
- Managers:
    - Homepage:
        icon: homepage.png
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:3000
        description: Dashboard principale
    - Dockge:
        icon: dockge
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:5001
        description: Gestione stack Compose
    - Portainer:
        icon: portainer.png
        href: https://{{HOMEPAGE_VAR_SYS_IP}}:9443
        description: Gestione container Docker
    - WUD:
        icon: whats-up-docker.png
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:3010
        description: Monitor aggiornamenti immagini

- Monitors:
    - LibreNMS:
        icon: librenms.png
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8020
        description: Network monitoring
    - Flame:
        icon: flame
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:5005
        description: Home secondaria

- Applications:
    - Excalidash:
        icon: dashboard-icons
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:6767
        description: Dashboard collaborativa
    - Fossflow:
        icon: flowise
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8060
        description: Diagrammi di processo
    - Omni Tools:
        icon: omni-tools
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8090
        description: Utility PDF/IMG/TXT/Video

- BIM&GIS:
    - OpenProject:
        icon: openproject
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8081
        description: Gestione progetto BIM
    - PostGIS CBU:
        icon: postgres.png
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:5433
        description: Database geospaziale
    - Ignition Gateway:
        icon: application-gateway-container.png
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8088
        description: SCADA gateway

- Multimedia:
    - Beets:
        icon: beets
        href: http://{{HOMEPAGE_VAR_SYS_IP}}:8337
        description: Gestione libreria musicale
