---
title: Telecontrollo Dashboard 
description: Collegamenti alle attività e utilità degli impianti di Irrigazione
startup: true
language: it
# showStats: true

# Tema
theme: dark
color: slate
groupsInitiallyCollapsed: false
statusStyle: "dot"
useEqualHeights: true
background:
  color: "#1e1e2e"

header:
  style: boxedWidgets  # opzioni: clean, boxed, underlined, boxedWidgets

target: _self

layout:

  Monitors:
    tab: Applications
    style: row
    columns: 4
    icon: factory

  Applications:
    tab: Applications
    style: row
    columns: 4
    icon: mdi mdi-application-edit

  BIM&GIS:
    tab: BIM&GIS
    style: row
    columns: 4
    icon: mdi mdi-account-hard-hat

  Multimedia:
    tab: Multimedia
    style: row
    columns: 4
    icon: mdi mdi-multimedia

  Managers:
    tab: Managers
    style: row
    columns: 4
    icon: mdi mdi-docker
 
# Mostra tutti i container Docker
docker:
  showAll: false
  refresh: 5000
