---
# Widget di ricerca e risorse di sistema
- search:
    provider: duckduckgo
    target: _blank
    focus: true
    showSearchIcon: true
    placeholder: "Cerca documentazione, issue e comandi..."

- datetime:
    text_size: sl
    locale: it-IT
    format:
      dateStyle: full
      timeStyle: medium
      hour12: false

- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    label: Trevi # optional
    latitude: 42.86566586745911
    longitude: 12.737591888271927
    timezone: Europe/Vatican # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
