services:
  geoserver:
    stdin_open: true
    tty: true
    networks:
      - iiot_internal
    ports:
      - 8080:8080
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ysld,ogcapi-features
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    image: docker.osgeo.org/geoserver:2.28.0
    restart: unless-stopped
    volumes:
      - ${APPDATA_DIR:-/opt/appdata}/geoserver_cbu/data:/opt/geoserver_data
    labels:
      - homepage.group=BIM&GIS
      - homepage.name=GeoServer
      - homepage.icon=specter-desktop  # mdi-target-variant # TODO cambiare
      - homepage.href=${GEOSERVER_HOMEPAGE_HREF:-http://${SYS_IP}:8080/geoserver}
      - homepage.description=GeoServer Docker Container
networks:
  iiot_internal:
    external: true
