services:
  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    container_name: portainer
    restart: unless-stopped
    ports:
      - ${PORTAINER_EDGE_PORT:-8000}:8000
      - ${PORTAINER_HTTPS_PORT:-9443}:9443
      - ${PORTAINER_HTTP_PORT:-9000}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer/data:/data
    labels:
      - "homepage.group=Managers"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.png"
      - "homepage.href=${PORTAINER_HOMEPAGE_HREF:-https://192.168.0.6:9443}"
      - "homepage.description=Docker Container Management"
      # - "homepage.widget.type=open"
      # - "homepage.widget.url=https://192.168.0.6:9443"
      # - "homepage.widget.fields={\"container\":\"portainer\",\"env\":\"my-docker\",\"endpoint\":3,\"key\":\"${PORTAINER_API_KEY}\"}"


