services:
  fossflow:
    image: stnsmith/fossflow:latest
    container_name: fossflow
    ports:
      - 8060:80
    volumes:
      - ${APPDATA_DIR:-/opt/appdata}/fossflow/diagrams:/data/diagrams
    restart: unless-stopped
    environment:
      - ENABLE_SERVER_STORAGE=true
      - STORAGE_PATH=/data/diagrams
    networks:
      - iiot_internal
    labels:
      - homepage.group=Applications
      - homepage.name=FOSSFlow
      - homepage.description=3D Flowchart Editor
      - homepage.icon=mdi-sitemap
      # - homepage.href=http://${SYS_IP:-127.0.0.1}:8060
      - homepage.href=http://${SYS_IP}:8060

networks:
  iiot_internal:
    external: true
